### ISSUE TITLE
Update CSV writer to use Struct

### ISSUE THREAD

**Issue by petya-** [dependulum/DASEA#21]
Use this package instead: https://pkg.go.dev/github.com/dnlo/struct2csv#section-readme

**Comment by svopper** [comment]
Or https://github.com/rocketlaunchr/dataframe-go

**Comment by heyjoakim** [comment]
@petya- can this be closed?

**Comment by petya-** [comment]
We put this on hold due to the issue we encountered with having to write all of the data at the end. However, we still use a package for the CSV writer, so we mitigate the original issues we were concerned with.

**Comment by petya-** [comment]
The branch that is WIP is: https://github.com/heyjoakim/DASEA/tree/change_csv_writer But we need to investigate other packages, this is not suitable for us: https://pkg.go.dev/github.com/dnlo/struct2csv#section-readme
